import { useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { format } from "date-fns";
import { Download, FileText, CalendarRange } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useExpenses, useExpenseStats } from "@/hooks/use-expenses";
import { useToast } from "@/hooks/use-toast";

const MONTHS = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"
];

export default function Reports() {
  const currentDate = new Date();
  const [selectedMonth, setSelectedMonth] = useState(currentDate.getMonth() + 1);
  const [selectedYear, setSelectedYear] = useState(currentDate.getFullYear());
  const { toast } = useToast();

  const { data: expenses } = useExpenses({ month: selectedMonth, year: selectedYear });
  const { data: stats } = useExpenseStats({ month: selectedMonth, year: selectedYear });

  const handleDownload = () => {
    if (!expenses || expenses.length === 0) {
      toast({
        title: "No Data",
        description: "There are no expenses to generate a report for this period.",
        variant: "destructive",
      });
      return;
    }

    const doc = new jsPDF();
    const monthName = MONTHS[selectedMonth - 1];

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text(`Monthly Expense Report`, 14, 20);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Period: ${monthName} ${selectedYear}`, 14, 28);
    
    // Summary Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(245, 247, 250);
    doc.roundedRect(14, 35, 182, 25, 3, 3, "FD");
    
    doc.setFontSize(10);
    doc.text("TOTAL EXPENSES", 20, 45);
    doc.text("TOTAL TRANSACTIONS", 100, 45);
    
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text(`Rs. ${stats?.total.toLocaleString()}`, 20, 53);
    doc.text(`${expenses.length}`, 100, 53);

    // Table
    const tableRows = expenses.map(expense => [
      format(new Date(expense.date), "dd/MM/yyyy"),
      expense.title,
      expense.category,
      `Rs. ${expense.amount}`
    ]);

    autoTable(doc, {
      startY: 70,
      head: [["Date", "Title", "Category", "Amount"]],
      body: tableRows,
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246], textColor: 255 },
      styles: { fontSize: 10, cellPadding: 3 },
      columnStyles: { 3: { halign: 'right' } },
    });

    // Footer
    const pageCount = doc.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by FinTrack on ${format(new Date(), "dd MMM yyyy")}`, 14, doc.internal.pageSize.height - 10);
    }

    doc.save(`Expenses_${monthName}_${selectedYear}.pdf`);
    
    toast({
      title: "Report Generated",
      description: "PDF has been downloaded successfully.",
    });
  };

  return (
    <div className="space-y-8 animate-in pb-20 md:pb-0">
      <div>
        <h1 className="text-3xl font-display font-bold text-foreground">Reports</h1>
        <p className="text-muted-foreground mt-1">Generate and download monthly statements</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="bg-white rounded-2xl border border-border/50 shadow-sm p-8 flex flex-col items-center text-center space-y-6">
          <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary mb-2">
            <FileText className="w-8 h-8" />
          </div>
          
          <div className="space-y-2">
            <h3 className="text-xl font-bold font-display">Monthly Statement</h3>
            <p className="text-muted-foreground text-sm max-w-xs mx-auto">
              Select a month and year to generate a detailed PDF report of all your expenses.
            </p>
          </div>

          <div className="flex gap-4 w-full max-w-sm">
            <Select value={selectedMonth.toString()} onValueChange={(v) => setSelectedMonth(parseInt(v))}>
              <SelectTrigger className="flex-1 rounded-xl">
                <SelectValue placeholder="Month" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                {MONTHS.map((month, idx) => (
                  <SelectItem key={month} value={(idx + 1).toString()}>{month}</SelectItem>
                ))}
              </SelectContent>
            </Select>

            <Select value={selectedYear.toString()} onValueChange={(v) => setSelectedYear(parseInt(v))}>
              <SelectTrigger className="flex-1 rounded-xl">
                <SelectValue placeholder="Year" />
              </SelectTrigger>
              <SelectContent className="rounded-xl">
                {[2023, 2024, 2025].map(year => (
                  <SelectItem key={year} value={year.toString()}>{year}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <Button 
            onClick={handleDownload}
            className="w-full max-w-sm rounded-xl py-6 text-base font-semibold shadow-lg shadow-primary/20 hover:shadow-xl hover:shadow-primary/30 transition-all"
          >
            <Download className="w-5 h-5 mr-2" /> Download PDF Report
          </Button>
        </div>

        {/* Info Card */}
        <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-2xl shadow-xl shadow-slate-900/10 p-8 text-white flex flex-col justify-between">
            <div className="space-y-4">
                <div className="w-12 h-12 bg-white/10 rounded-xl flex items-center justify-center backdrop-blur-md border border-white/10">
                    <CalendarRange className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-2xl font-bold font-display">Why Monthly Reports?</h3>
                <ul className="space-y-3 text-slate-300 text-sm leading-relaxed">
                    <li className="flex gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5" />
                        Track your spending patterns over time
                    </li>
                    <li className="flex gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5" />
                        Prepare for tax filing with accurate records
                    </li>
                    <li className="flex gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-primary mt-1.5" />
                        Analyze category-wise breakdown to save money
                    </li>
                </ul>
            </div>
            
            <div className="mt-8 pt-6 border-t border-white/10">
                <p className="text-xs text-slate-400 font-mono">
                    System Status: All systems operational
                </p>
            </div>
        </div>
      </div>
    </div>
  );
}
